import os

ACCESS_TOKEN = os.getenv('ACCESS_TOKEN', 'YOUR_ACCESS_TOKEN')
VERIFY_TOKEN = os.getenv('VERIFY_TOKEN', 'YOUR_VERIFT_TOKEN')
WIT_ACCESS_TOKEN = os.getenv('WIT_ACCESS_TOKEN', 'YOUR_WIT_ACCESS_TOKEN')

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8000
