import os

ACCESS_TOKEN = os.getenv('ACCESS_TOKEN', 'YOUR_ACCESS_TOKEN')
VERIFY_TOKEN = os.getenv('VERIFY_TOKEN', 'YOUR_VERIFT_TOKEN')

DIALOGFLOW_TOKEN = os.getenv('DIALOGFLOW_TOKEN', 'YOUR_DIALOGFLOW_TOKEN')

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8000
